"""
Elder Coxson is a bit more chilled out now, but still not playing
"""

import dashboard

messenger_ids = {
    dashboard.Zone.ZONE_1: '2419609848082592',
    dashboard.Zone.ZONE_2: '4954822721225549',
    dashboard.Zone.ZONE_3: '5865277466887042',
    dashboard.Zone.ZONE_4: '1363317190447129',
    dashboard.Zone.ZONE_5: '5936540856451995',
    dashboard.Zone.ZONE_6: '4133470603409493',
    dashboard.Zone.ZONE_7: '4145470815511596',
    dashboard.Zone.ZONE_8: '24976215742026849',
}

morning = [
    'Goooooood morning',
    'Rise and grind',
    'Hello',
    'Good morning',
    'Greetings',
    '*yawn* morning',
    'Wakey, wakey, eggs and bakey!',
    'Top of the morning to you!',
    'Morning, sunshine!',
    'Good day, mate!',
    "Up and at 'em!",
    'Another day, another dollar!',
    'Rise and shine! The cougars are out!',
    'Time to seize the day!',
    'Time to serve the Lord with all your heart!',
    'Good morning, future bringers of joy!',
    "Rise and shine, it's time to find!",
    'Time to bring the gospel to the world!',
    'The field is white, let’s get to work!',
    'Good morning, missionaries! Ready to change lives?',
    'Another day, another opportunity to serve!',
    'Another day, another slay',
    'Another beautiful day in the neighborhood!',
    'The early bird catches the worm!',
    'Mornin’, y’all!',
    'The Lord has big plans for today—let’s get started!',
    'Good morning, soldiers of faith!',
]

score_intro = [
    "Here's the score:",
    "Score... let's see",
    "I bet we're winning, let's check",
    "Let's check those scores",
    'Time to see how we’re doing!',
    'Let’s tally up the wins!',
    'What’s the score today?',
    'Let’s see the results!',
    'How are we stacking up?',
    'Score time—who’s leading?',
    'Let’s check our progress!',
    'Ready to see the numbers?',
    'Let’s check the scoreboard!',
    'Let’s see how the team’s performing!',
    'What’s the latest update?',
    'Time for a score check!',
    'Let’s see the fruits of our labor!',
    'How did we fare today?',
    'Let’s take a peek at the results!',
    'Let’s see how today’s shaping up!',
    'Time to crunch the numbers!',
]

referrals = [
    'Time to check the referrals!',
    "I bet there's no referrals in this list...",
    "Let's take a look at the referral list",
    'Referrals referrals referrals',
    'Look at all the people that need to be contacted!',
    "Let's dive into those referrals!",
    'Who’s ready to find some golden contacts?',
    'Time to uncover the next miracle!',
    'Let’s see who the Lord has prepared for us today!',
    'Let’s see who’s eager to hear the good news!',
    'Time to connect with those who are seeking truth!',
    'Time to check in on our future friends!',
    'Time to bring some light into their lives!',
    'Time to find those searching for answers!',
    "Let's get to it!",
    'Send your favorite animal emoji in the chat once you have a contact in!',
    'Time to show these children of God some love!',
    'I bet thse people will be contacted faster than I can fetch the ball.',
    'First one to contact these people wins a slobbery tennis ball!',
    'Ready, set go!',
]


outro = [
    'See you tomorrow, have a finding day!',
    'Until next time, see you later!',
    'Thanks for being amazing!',
    'Catch you on the flippity flip',
    'Have a finding day!',
    'Bye bye now',
    'See you real soon!',
    "That's all, folks!",
    'I bid you a very heartfelt good night (day ig)',
    'Be well, do good work, and keep in touch.',
    "In case I don't see you... Good afternoon, good evening, and good night!",
    "Roads? Where we're going, we don't need roads.",
    'The adventure continues.',
    'Stay awesome, and see you soon!',
    'Take care and keep shining!',
    'Onward and upward!',
    'On to eternal perfection!',
    'Keep the good vibes going!',
    'Goodbye for now, but not forever!',
    'May the force be with you',
    'Stay safe, stay happy, stay you!',
    'Until we meet again, God be with you!',
    'Stay strong, and keep sharing the good word!',
    'Onward Christian soldiers!',
    'Until we chat again, keep planting seeds of faith!',
    'May your days be full of miracles!',
    'Go and do, the Lord will provide!',
    'Stay faithful, and the blessings will come!',
    'Remember to contact your referrals ASAP! (no pressure)',
]

blank_slates = [
    "I'm going to wag my tail all day!",
    "I want to give you all treats! Too bad I'm out of MSF...",
    "I'm so happy that I'm going to wag my tail with all of these people in heaven!",
    "Yaaaaaay!!!!",
    "Good work! I am very pround to have you as my humans.",
    "Let's keep it going!",
    "Your zone is so fire at SMF!",
    "That's a miracle right there!",
    "You are awesome now, in 20 years, and forever!",
]
